spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catty
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

photo:
  path:
    cat: c:/cat
    obsLog: c:/obsLog
    insLog: c:/insLog